apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    component: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        component: kube-proxy
        tier: node
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - command:
        - "/hyperkube"
        - proxy
        - "--kubeconfig=/var/lib/kubelet/kubeconfig"
        - "--cluster-cidr=<kubeClusterCidr>"
        - "--feature-gates=ExperimentalCriticalPodAnnotation=true"
        image: "<kubernetesHyperkubeSpec>"
      <kubernetesHyperkubeEnvVariableTag>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_CONTAINERSERVICE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_CONTAINERSERVICE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_CONTAINERREGISTRY_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_CONTAINERREGISTRY_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_DISK_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_DISK_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_SCALESET_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_SCALESET_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_STORAGE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_STORAGE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_STORAGE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_STORAGE_Value>
        <kubernetesHyperkubeEnv_AZURE_ENVIRONMENT_FILEPATH_Tag>
          <kubernetesHyperkubeEnv_AZURE_ENVIRONMENT_FILEPATH_Value>       
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/etc/ssl/certs"
          name: ssl-certs-host
          readOnly: true
        - mountPath: "/etc/kubernetes"
          name: etc-kubernetes
          readOnly: true
        - mountPath: "/var/lib/kubelet/kubeconfig"
          name: kubeconfig
          readOnly: true
      hostNetwork: true
      volumes:
      - hostPath:
          path: "/etc/ssl/certs"
        name: ssl-certs-host
      - hostPath:
          path: "/var/lib/kubelet/kubeconfig"
        name: kubeconfig
      - hostPath:
          path: "/etc/kubernetes"
        name: etc-kubernetes
      nodeSelector:
        beta.kubernetes.io/os: linux
