apiVersion: "v1"
kind: "Pod"
metadata:
  name: "kube-controller-manager"
  namespace: "kube-system"
  labels:
    tier: control-plane
    component: kube-controller-manager
spec:
  hostNetwork: true
  containers:
    - name: "kube-controller-manager"
      image: "<kubernetesHyperkubeSpec>"
      <kubernetesHyperkubeEnvVariableTag>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_CONTAINERSERVICE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_COMPUTE_CONTAINERSERVICE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_CONTAINERREGISTRY_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_CONTAINERREGISTRY_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_DISK_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_DISK_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_SCALESET_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_NETWORK_SCALESET_Value>
        <kubernetesHyperkubeEnv_APIVERSION_ARM_STORAGE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_ARM_STORAGE_Value>
        <kubernetesHyperkubeEnv_APIVERSION_STORAGE_Tag>
          <kubernetesHyperkubeEnv_APIVERSION_STORAGE_Value>
        <kubernetesHyperkubeEnv_AZURE_ENVIRONMENT_FILEPATH_Tag>
          <kubernetesHyperkubeEnv_AZURE_ENVIRONMENT_FILEPATH_Value>          
      command: ["/hyperkube", "controller-manager"]
      args: [<kubernetesControllerManagerConfig>]
      volumeMounts:
        - name: "etc-kubernetes"
          mountPath: "/etc/kubernetes"
        - name: "var-lib-kubelet"
          mountPath: "/var/lib/kubelet"
        - name: msi
          mountPath: "/var/lib/waagent/ManagedIdentity-Settings"
          readOnly: true
        - name: "ssl"
          mountPath: "/etc/ssl/certs"
          readOnly: true 
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "var-lib-kubelet"
      hostPath:
        path: "/var/lib/kubelet"
    - name: msi
      hostPath:
        path: "/var/lib/waagent/ManagedIdentity-Settings"
    - name: ssl
      hostPath:
        path: "/etc/ssl/certs"
